### ISSUE TITLE
what this code do?

### ISSUE THREAD

**Issue by quinnj** [BioJulia/Libz.jl#2]
First off, I'm really excited about this.

What do you think about just having a single `Libz.Stream` type? Perhaps parameterized by inflate/deflate that supports reading and writing? Maybe I can dive into the code more and see what this would take; everything looks pretty clean though.

Also thoughts on registering the package? Timeline?

**Comment by dcjones** [comment]
It would make the interface nicer to have just a Stream type, but it may be tricky. The stream interface I'm using is fast because the buffering it uses is pretty simple and transparent, so e.g. zlib can read/write directly to/from the buffer. Reading and writing with the same stream complicates things because you have to worry much more about flushing buffers at the right time. It may be doable though.

This package is "done" (as in, does what it needs to do, probably doesn't have serious bugs), so I could register it whenever. I was hesitating because I'm considering renaming this to Zlib.jl and replacing the old Zlib.jl. I'd have to make PRs against everything that uses Zlib.jl, and add julia 0.3 compat to this library, though.

**Comment by quinnj** [comment]
I guess the good thing about the Stream type is that it can always be added later as another layer on top of the others.

I actually kind of like the name Libz.jl and it would certainly be less work just putting it up, deprecating GZip & Zlib, and letting things go organically from there.
