### ISSUE TITLE
define Base.nb_available

### ISSUE THREAD

**Issue by tpapp** [BioJulia/Libz.jl#54]
Currently [CSV.jl](https://github.com/JuliaData/CSV.jl) does not work with `Libz` inflated input streams (ie gzipped CSV files). @joshbode [suggested](https://discourse.julialang.org/t/how-to-subset-a-stream-i-o-and-pass-it-to-tensorflow-jl-question-has-been-updated/3502/27?u=tamas_papp)  a workaround:
```julia
Base.nb_available{T <: Libz.Source}(s::BufferedStreams.BufferedInputStream{T}) = eof(s) 
```
I don't know how general or efficient this is, but having something that has the same effect in the library would be nice.

**Comment by joshbode** [comment]
(cough) that should be `!eof(s)`, which was my mistake in the [forum](https://discourse.julialang.org/t/how-to-subset-a-stream-i-o-and-pass-it-to-tensorflow-jl-question-has-been-updated/3502/37?u=joshbode) :), e.g.

```julia
Base.nb_available{T <: Libz.Source}(s::BufferedStreams.BufferedInputStream{T}) = !eof(s)
```
It doesn't appear to affect the performance of CSV.jl at least, since as far as I can tell it is only used there once to determine whether the stream is already exhausted before getting the header line.

**Comment by bicycle1885** [comment]
Close this issue. However, I'd rather recommend using [CodecZlib.jl](https://github.com/bicycle1885/CodecZlib.jl), which also supports `nb_available`, and [TranscodingStreams.jl](https://github.com/bicycle1885/TranscodingStreams.jl) supports .bz2, .xz, .zstd, etc. with the same interface.
