### ISSUE TITLE
some gz files cannot be read correctly

### ISSUE THREAD

**Issue by sfchen** [BioJulia/Libz.jl#9]
[R1.fastq.gz](https://github.com/BioJulia/Libz.jl/files/66241/R1.fastq.gz)

See attached `R1.fastq.gz`, this file cannot be read correctly using Libz. This file has `4476*4` lines, but Libz can only read `38*4` lines then it will report `EOF`.

If I gunzip it to R1.fastq, and then zip it using Libz, then it is readable by Libz.

**Comment by sfchen** [comment]
This file is directly output by Illumina `bcl2fastq`, so it is a typical fastq gz file

**Comment by bicycle1885** [comment]
Thank you for your report. This is reproducible in my computer.

I'm not sure why this happens at the moment, but one solution is using `reset_on_end=true` as follows:

``` julia
    s = ZlibInflateInputStream(open("R1.fastq.gz"))
    @show length(readall(s))
    s = ZlibInflateInputStream(open("R1.fastq.gz"), reset_on_end=true)
    @show length(readall(s))
```

output

```
length(readall(s)) = 13206
length(readall(s)) = 1521399
```

I'll continue to investigate the reason.

**Comment by quinnj** [comment]
Any update on this? I have a reproducible case as well. If you can even point to the methods where the reading/EOF-setting is happening, I'm happy to try and dig in as well.

**Comment by dcjones** [comment]
I think this is actually not unexpected behavior, but an awkward result of trying to accommodate all gzip/zlib use cases in one interface.

Likely `bcl2fastq` outputs gz files that are a concatenation of zlib streams (e.g. this in what bgzf does), which is a valid gzip file and gzip tools will handle automatically, but the lower level zlib interface will not automatically deal with.

The default behavior of this library mimics the lower level zlib interface and stops at the end of the first zlib stream, but I added the option `reset_on_end` to mimic the gzip interface which checks for another stream after the current one ends.

Maybe there should be a separate convenience interface for gzip files, since `reset_on_end` isn't obvious.

**Comment by timbitz** [comment]
Yes I noticed this as well with some fastq files... It looked to agree with the explanation by @dcjones regarding cat'ed gzipped files:

``` bash
seq 1 10 | tee -a file1.txt >> file2.txt
cat file{1,2}.txt | gzip -c > pre-gz.txt.gz
gzip file{1,2}.txt
cat file{1,2}.txt.gz > post-gz.txt.gz

gzip -dc pre-gz.txt.gz | wc -l
gzip -dc post-gz.txt.gz | wc -l
```

20
20

but

``` julia
using Libz

function countlines( stream )
   count = 0
   for l in eachline( stream )
      count += 1
   end
   count
end

pre = open( "pre-gz.txt.gz" ) |> ZlibInflateInputStream
println( countlines( pre ) )

post = open( "post-gz.txt.gz" ) |> ZlibInflateInputStream
println( countlines( post ) )
```

20
10

**Comment by bicycle1885** [comment]
I think setting `reset_on_end=true` by default would be better to avoid the pitfall. I'd like to merge #18 if no objections.

**Comment by TransGirlCodes** [comment]
:+1:
